CREATE TABLE app_user
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_app_user PRIMARY KEY (id)
);

CREATE TABLE comments
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    text    VARCHAR(255)                            NOT NULL,
    date    date                                    NOT NULL,
    user_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_comments PRIMARY KEY (id)
);

CREATE TABLE post
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    posttext VARCHAR(255)                            NOT NULL,
    date     TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    user_id  BIGINT,
    CONSTRAINT pk_post PRIMARY KEY (id)
);

ALTER TABLE comments
    ADD CONSTRAINT FK_COMMENTS_ON_USER FOREIGN KEY (user_id) REFERENCES app_user (id);

ALTER TABLE post
    ADD CONSTRAINT FK_POST_ON_USER FOREIGN KEY (user_id) REFERENCES app_user (id);