CREATE TABLE post
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    posttext VARCHAR(255)                            NOT NULL,
    date     date                                    NOT NULL,
    user_id  BIGINT                                  NOT NULL,
    CONSTRAINT pk_post PRIMARY KEY (id)
);

ALTER TABLE post
    ADD CONSTRAINT FK_POST_ON_USER FOREIGN KEY (user_id) REFERENCES app_user (id);

